# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

networks:
  goalong_network:
    driver: bridge


services:
  
  goalongdb:
    image: goalongdb
    ports:
      - 1433:1433
    networks:
      - goalong_network


  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - goalong_network

  goalongapp:
    image: goalongwebapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7046:6600
    depends_on:
      - goalongdb
      - rabbitmq
    environment:
      - RabbitMQ__HostName=rabbitmq
    networks:
      - goalong_network