# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  
  goalongdb:
    image: goalongdb
    ports:
      - 1433:1433

  goalongapp:
    image: goalongwebapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7046:6600
    depends_on:
      - goalongdb